table 'Hospital ER_Data'
	lineageTag: 3adf379f-630e-4e23-8605-7256b91202ed

	measure 'Number of Patients' = COUNT('Hospital ER_Data'[Patient Id])
		formatString: 0
		lineageTag: 7af60aea-b116-4472-8c5e-a51b1d9b016a

	measure referred = CALCULATE(COUNTROWS('Hospital ER_Data'),('Hospital ER_Data'[Department Referral]) <> "None")
		formatString: 0
		lineageTag: e44dbab1-b2af-407d-8f0a-9c442a5dba4b

	measure 'Avg Wait Time' = FORMAT(AVERAGE('Hospital ER_Data'[Patient Waittime]), "0.0" & " Min")
		lineageTag: 3a81a432-9ccc-4e51-a69b-634cc8151237

	measure 'satisfaction score' = AVERAGE('Hospital ER_Data'[Patient Satisfaction Score])
		lineageTag: b190672e-8290-4af7-be0a-a613e47c0ff3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Patient Id'
		dataType: string
		lineageTag: c7b1dc9e-a8af-4608-9014-aff2b47ac7a7
		summarizeBy: none
		sourceColumn: Patient Id

		annotation SummarizationSetBy = Automatic

	column 'Patient Admission Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: af65d062-be6a-453b-bfc0-26cfa173af31
		summarizeBy: none
		sourceColumn: Patient Admission Date

		variation Variation
			isDefault
			relationship: d88b6ad7-9888-4829-b0d7-cfa3c1dd114a
			defaultHierarchy: LocalDateTable_afd553c4-88ce-454e-8cd8-ddcf43011420.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Patient First Inital'
		dataType: string
		lineageTag: af109be0-b71c-4198-9529-6014f3407520
		summarizeBy: none
		sourceColumn: Patient First Inital

		annotation SummarizationSetBy = Automatic

	column 'Patient Last Name'
		dataType: string
		lineageTag: f4f0c7ab-d659-41b7-8e96-52b0f1b168d5
		summarizeBy: none
		sourceColumn: Patient Last Name

		annotation SummarizationSetBy = Automatic

	column 'Patient Gender'
		dataType: string
		lineageTag: 49163eac-a25c-4325-a532-6fb023db7925
		summarizeBy: none
		sourceColumn: Patient Gender

		annotation SummarizationSetBy = Automatic

	column 'Patient Age'
		dataType: int64
		formatString: 0
		lineageTag: d2520bbf-35f8-40fc-bf90-929ecc91672a
		summarizeBy: none
		sourceColumn: Patient Age

		annotation SummarizationSetBy = User

	column 'Patient Race'
		dataType: string
		lineageTag: d1150fce-7b93-4aba-a218-fa41ca217aab
		summarizeBy: none
		sourceColumn: Patient Race

		annotation SummarizationSetBy = Automatic

	column 'Department Referral'
		dataType: string
		lineageTag: 2195eeac-3639-49f0-8689-384523077096
		summarizeBy: none
		sourceColumn: Department Referral

		annotation SummarizationSetBy = Automatic

	column 'Patient Admission Flag'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 2c3f4c3a-e217-4521-8298-f1b452e62c70
		summarizeBy: count
		sourceColumn: Patient Admission Flag

		annotation SummarizationSetBy = User

	column 'Patient Satisfaction Score'
		dataType: int64
		formatString: 0
		lineageTag: b6bdcd09-4265-4aab-af66-eb70f4e7d395
		summarizeBy: sum
		sourceColumn: Patient Satisfaction Score

		annotation SummarizationSetBy = Automatic

	column 'Patient Waittime'
		dataType: int64
		formatString: 0
		lineageTag: c642e345-a2f7-40f2-84fb-3903ace79f80
		summarizeBy: sum
		sourceColumn: Patient Waittime

		annotation SummarizationSetBy = Automatic

	column 'Patients CM'
		dataType: int64
		formatString: 0
		lineageTag: 4860ea12-8005-4bdb-8a57-0a1c69d7e077
		summarizeBy: sum
		sourceColumn: Patients CM

		annotation SummarizationSetBy = Automatic

	column 'Patient Full Name'
		dataType: string
		lineageTag: 9a47b4f1-5c82-4a1f-867f-1c7a041f73c7
		summarizeBy: none
		sourceColumn: Patient Full Name

		annotation SummarizationSetBy = Automatic

	column 'Patient Admit Date' = date(YEAR('Hospital ER_Data'[Patient Admission Date]), MONTH('Hospital ER_Data'[Patient Admission Date]), day('Hospital ER_Data'[Patient Admission Date]))
		formatString: Long Date
		lineageTag: 7be54ffc-8530-49c7-9ac3-628448c4db5c
		summarizeBy: none

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Age Groups' =
			
			SWITCH (
			    TRUE(),
			    'Hospital ER_Data'[Patient Age] >= 100, "100+",
			    'Hospital ER_Data'[Patient Age] >= 90,  "90-99",
			    'Hospital ER_Data'[Patient Age] >= 80,  "80-89",
			    'Hospital ER_Data'[Patient Age] >= 70,  "70-79",
			    'Hospital ER_Data'[Patient Age] >= 60,  "60-69",
			    'Hospital ER_Data'[Patient Age] >= 50,  "50-59",
			    'Hospital ER_Data'[Patient Age] >= 40,  "40-49",
			    'Hospital ER_Data'[Patient Age] >= 30,  "30-39",
			    'Hospital ER_Data'[Patient Age] >= 20,  "20-29",
			    'Hospital ER_Data'[Patient Age] >= 10,  "10-19",
			    "0-9"
			)
		lineageTag: 781e5217-a26e-4ba5-bf75-159fd7cc3caa
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Admit Status' = IF('Hospital ER_Data'[Patient Admission Flag] = TRUE, "Admitted", "Not Admitted")
		lineageTag: e5baca61-1cb5-4483-85df-1b5de915ce05
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Wait time status' = if ('Hospital ER_Data'[Patient Waittime] <=30, "Within Target", "Missed Target")
		lineageTag: 55105c08-8acb-4636-af09-377afde06fa1
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Admission hour' = HOUR('Hospital ER_Data'[Patient Admission Date])
		formatString: 0
		lineageTag: b3278fd6-bcf9-4786-8da0-e52f8e42d1cd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Wait Time interval' =
			SWITCH( True(),'Hospital ER_Data'[Admission hour]<=2 , "00-02",
			'Hospital ER_Data'[Admission hour]<=4 , "03-04",
			'Hospital ER_Data'[Admission hour]<=6 , "05-06",
			'Hospital ER_Data'[Admission hour]<=8 , "07-08",
			'Hospital ER_Data'[Admission hour]<=10 , "09-10",
			'Hospital ER_Data'[Admission hour]<=12 , "11-12",
			'Hospital ER_Data'[Admission hour]<=14 , "13-14",
			'Hospital ER_Data'[Admission hour]<=16 , "15-16",
			'Hospital ER_Data'[Admission hour]<=18 , "17-18",
			'Hospital ER_Data'[Admission hour]<=20 , "19-20",
			'Hospital ER_Data'[Admission hour]<=22 , "21-22",
			'Hospital ER_Data'[Admission hour]<=24 , "23-24",
			"Above 24"
			)
		lineageTag: 6c3f5a76-1592-4b8e-a84a-81001efc8009
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition 'Hospital ER_Data' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Geetika\Downloads\healthcare analytics\Hospital ER_Data.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Patient Id", type text}, {"Patient Admission Date", type datetime}, {"Patient First Inital", type text}, {"Patient Last Name", type text}, {"Patient Gender", type text}, {"Patient Age", Int64.Type}, {"Patient Race", type text}, {"Department Referral", type text}, {"Patient Admission Flag", type logical}, {"Patient Satisfaction Score", Int64.Type}, {"Patient Waittime", Int64.Type}, {"Patients CM", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Patient Full Name", each [Patient First Inital]&" "&[Patient Last Name]),
				    #"Replaced Value" = Table.ReplaceValue(#"Added Custom","M","Male",Replacer.ReplaceText,{"Patient Gender"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","F","Female",Replacer.ReplaceText,{"Patient Gender"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","NC","Not Disclosed",Replacer.ReplaceText,{"Patient Gender"})
				in
				    #"Replaced Value2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

